version: Build {build}
configuration: Release
platform: x64
build:
  project: .\Plugin\reaper_ultraschall\reaper_ultraschall.sln
  parallel: true
  verbosity: normal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
  