version: '{build}'
configuration: Release
platform: x64
before_build:
- cmd: git submodule update --init
build:
  project: .\Plugin\reaper_ultraschall\reaper_ultraschall.sln
  parallel: true
  verbosity: normal