version: Build {build}
configuration: Release
platform: x64
before_build:
- cmd: >-
    git submodule update --init

    call .\Plugin\reaper_ultraschall\Submodules\curl\projects\generate.bat vc14
build:
  project: .\Plugin\reaper_ultraschall\reaper_ultraschall.sln
  parallel: true
  verbosity: normal
notifications:
- provider: Slack
  auth_token:
    secure: MREXfm5HrzEJO4xqhTsrPQElWfzgv1IDoxfXcr0qUL3ThLBIFJUYPp/ZEyBB7TxkvDuaAWKu8C1IueWPy02USA==
  channel: '#github'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true